name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "f18cfa1791ae663a1e4c0265a3e3eeb8"

[vars]
WORKER_URL = "https://line-crm-worker.usami-crm.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "32408f39-9cfa-4a82-b0fd-ae1b22638bd5"

[triggers]
crons = ["*/5 * * * *"]
